image: node:14

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm i
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
